
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27  
    - CONDA_PY=34  
    - CONDA_PY=35  
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "fKJGTwQLTdTE74bnZ9lYNFPn+ekzBHlUWJbPeJMNajNnWut7IwwPV+6hAmpPEamNHi15vSUDMB8rxv2OoY6hjgvBfR1e+37I18jFEUi/w5rTTbWiy+D7CR4ypK1cHcBSHAYod9GRKHkiKcHlj5fxSDEAggB6pdjYIQCIIIb2C96XfQMQITKOB1gvvZS2Ryl+Njw1Ar+/itBMh7YxrFNWUk6XglDo1Zo2TC1WB8Qme4J4ao90cNaqPqFNH2ruqKLCh8dqOGrIU9JtMaKQvYQZ7S+nFrdk0m5aoW3a7BRb9B+NUgh0ZTn+HjrTT2mVXXgK6zUjp8GlfW+Q3V4c5wkaa0QQ4jT4WkeE224JWOcJYoWTKUVKpiViApoUXWlLfIlqWWlJx5vMRTuLwwDwV3Jzpo8S5jYCv2Ak/guIE+Ph4CY2vSck2lC8B1qscOjr1XLzydhBGOc9IDFxmWpNex7xR9rgrWHZAVQGn08Ldc/xdl1EV6hCShX7fN6YFa1+cEop9I3r3guRHh/cHhknIa9fNwIRGyPLtIY9VFk/XQRX0QpVxtFbkpSNsQSZIjKgvsfvYYF1Gh3CxA8dixLCSppScdSfl2ihjU9/5dpmpUrBVMJjeps4D+O7b+zUqJdaLFy12MQWpS3wasY39mFvPn3g7DY2/SSRHih29FmPdIIT8ng="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
