travis:
  secure:
    BINSTAR_TOKEN: XhpjCbN+tbDNfTXqdWUBtoDFqZkaWEjkHf1CtXhKu68VbwguCdb641L4cwlJfbwZl5HaMiQGT/G9wBHG2njRmV8VSKQAa69/apPYYicRvzkCy6PsBNRO/s8Lab+rIxdynVPY7tq9vvntqXNMb2a5KYgj44cEAH5ZTo7z6eFSU54c/FngVjoKIGbeO1IqzbRgVse7AXLslW0JdNYlbFhjwCTYbdQ/gd4rbeNF1oQZj5gT2Va2xuGN4CWitnHwVSMAnP1J7/qWnHGLGehwz6/B+YFjTGZlUvtiOFTna1z23IGQcYCWlKcQWt8ojzOpwpsd4jLrbA9ZH5Zt8ZRnWqP7LNeA4+b9ciHYuNf2zvh6rK+sxTMWViuuO+nlZxRjHjhqHkYbyHA+Qz56402j1XjNo3K5nb0t5w1njV4H26Tt1G91rZQa0svjSIGMuz/vctMSQ5WpZ0EFzcatKUY7fBa7pKRt9GBTlTWYUWb6icA0WmYBC8WyH9OlB7AH9DiVvZokRJwTmBerpUg0Dv3j9qnmCkzpAgA12YdPDRB4cQ3jE9wKMWLLZoAHdSolTeZvpXI4YReiZtCzM374bPV5I+w+qa4j2+LpkGgZHtyGcoliC2U0Q7qnI3KkDiWexkP7OLTB3NKe5Mur00NFWslmHSdINhM8R6uTqO7vUCRHzAt/2mc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
