travis:
  secure:
    BINSTAR_TOKEN: HlhC/aR1FsWMryYQma/kE9kAjphq6suyNrPjEmFPXa2xTVIEPw7fdRIKe9Hz1Jdw+/HH8lIDw7vQ7B4UT+ELjiUbDTzvuBo2JMWRqsZ5M+xs1Jwshq3vmn6TXGYbf4U2M+M+3GvOrTFH66n6CXbJ2cJkmSCUhJKy0CHnpYC8LIE9uOVvS8VwXCwIE3WjNiOqJqkybj9cVnTTeB2ij2gSAtoi3uz4w3PS9khd0Or2j2wGfde5qZY+yDYJSmtZ0q7Ql4wk+gx8VBZqhv1MwxkM3SimGjMVokyRBjf8JLG9gS4QDBsQVdtgvm+jiYC+wtZLtNAhoex0grTwQTos6BEWxLKYooU/nvOHEsml/2HsKvQO9YdlpLrqIEJiSE8GsHPTQSanui10qbjwFjlwhVj5iX24NupjhTyWFDZhEGeT+Dv67NT9Q79hLkNXLnvQJ5u0JNbn9sgBeZX1/tcSJBjnfRS3m1W2Mwcm1q+G2CgbU05IJwHGGsVEQe6t7hPrSoSP0vsfIskUxMzHTernn6HztSRT8miVN6qbl2mxFkqqVOy+5N3sXf12ljfsn99LZXra+mFAZ7U39DnxRf5QUFcbTZ9/GjQpxLk4Ln1wr9Fw2PHjdvhlburEpI3ffRYsG7wMVJjXyN7KSrZjxxs6+eBiPMri33tDBmXxWKYQ8x5rfic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
