travis:
  secure:
    BINSTAR_TOKEN: eQ+WkL4tiy66fixQsza57zLiRSfwDTx7coSFg9AK7+a7cqbMrU6B8JI7OIGNbJoKqdtpZLrs0GsNk34LCyHtwgsE8lp7IW7TTfeBvBDY33YDp3JD1ERyw92VTViVPArPIBgmHzwphS5VWHrptbYHVe6gaXnmHqlCWydnFdQ33LQ9UsbfoR7N7DT3SrfQifVa+kggwh5dHVhNpTmZ0d9z5JgYG8uN9EQRQF7t4I8SVRu+su+DrhwMRzNqsbjwx/7LmC/yiECaPNQzMYfQxPiKE3+7xX/hWRHfbSXnnASv9weMP0YxQrY1JtLi7M4C/cenBnbbC2NStcAsAG4NQPA5mA7xNdis8VwP+hd09x/MZqasBzPUQd1ZKbh9zWbSlKqx+AtOHofEMzmxmfSkgeC1zJXeCDykw/jEUjkOFb6KpCfH5jNghEeUDlpdtaRhXqFccx7PyLJMnYv6pOqkdnFxQIlEjG92Z6KNQAkkS5/yex7V7RLuK+s6PunfbAMklkPPmzZLtt1/xBbY/l1EKCCsTbI7h/cSCrrkZfr9L6YCPUreMKFtVavAQQFMVktfq730lE0KQGggks28sJF4XMmINCPbGHgMccJn6EoX/fqYVjLqpDbaL+8FcdA+wh1DX+SatRS1bSuDIhgPtzJGGrQqrubopZ9RXzNeRHtQ3aYNkWc=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
